/**
 * Each new term in the Fibonacci sequence is generated by 
 * adding the previous two terms. By starting with 1 and 2, 
 * the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose 
values do not exceed four million, find the sum of the 
even-valued terms.
 */

public class Fib {
    
    public Fib(int n) {
        // Create a Fibonacci sequence up to n
        int a = 1;
        int b = 1;
        int c = 0;
        int sumOfEvens = 0;
        while (c < n) {
            c = a + b;
            if (c < n) {
                a = b;
                b = c;
                if (c % 2 == 0) {
                    System.out.println(c);
                    sumOfEvens = sumOfEvens + c;
                }
            }
        }
        System.out.println("Sum: " + sumOfEvens);
        
    }
    
}